'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Pizza_Mania_new.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1723876() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1723876", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1723876red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1723876red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _7UP_500ML_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("7UP(500ML)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _7UP_500ML_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("7UP(500ML)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _7UP_500ML_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("7UP(500ML)2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bill_panel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bill panel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bill_panel1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bill panel1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CHEESE_N_CORN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHEESE N CORN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CHEESE_N_CORN1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHEESE N CORN1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CHEESE_N_CORN2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHEESE N CORN2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CHICKEN_DOMINATOR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHICKEN DOMINATOR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CHICKEN_DOMINATOR1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHICKEN DOMINATOR1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CHICKEN_DOMINATOR2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHICKEN DOMINATOR2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CHICKEN_DOMINATOR3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHICKEN DOMINATOR3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CHICKEN_FIESTA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHICKEN FIESTA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CHICKEN_FIESTA1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHICKEN FIESTA1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CHICKEN_FIESTA2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHICKEN FIESTA2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CHICKEN_GOLDEN_DELIGHT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHICKEN GOLDEN DELIGHT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CHICKEN_GOLDEN_DELIGHT1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHICKEN GOLDEN DELIGHT1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CHICKEN_GOLDEN_DELIGHT2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHICKEN GOLDEN DELIGHT2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CHICKEN_PEPPERONI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHICKEN PEPPERONI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CHICKEN_PEPPERONI_STUFFED_GARLIC_BREAD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHICKEN PEPPERONI STUFFED GARLIC BREAD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CHICKEN_PEPPERONI_STUFFED_GARLIC_BREAD1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHICKEN PEPPERONI STUFFED GARLIC BREAD1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CHICKEN_PEPPERONI1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHICKEN PEPPERONI1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CHICKEN_PEPPERONI2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHICKEN PEPPERONI2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CHICKEN_SAUSAGE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHICKEN SAUSAGE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CHICKEN_SAUSAGE1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHICKEN SAUSAGE1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CHICKEN_SAUSAGE2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHICKEN SAUSAGE2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property danger() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("danger", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DELUXE_VEGGIE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DELUXE VEGGIE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DELUXE_VEGGIE1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DELUXE VEGGIE1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DELUXE_VEGGIE2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DELUXE VEGGIE2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DOUBLE_CHEESE_MARGHERITA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DOUBLE CHEESE MARGHERITA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DOUBLE_CHEESE_MARGHERITA1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DOUBLE CHEESE MARGHERITA1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DOUBLE_CHEESE_MARGHERITA2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DOUBLE CHEESE MARGHERITA2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DOUBLE_CHEESE_MARGHERITA3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DOUBLE CHEESE MARGHERITA3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DOUBLE_CHEESE_MARGHERITA4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DOUBLE CHEESE MARGHERITA4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FARM_HOUSE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FARM HOUSE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FARM_HOUSE1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FARM HOUSE1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FARM_HOUSE2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FARM HOUSE2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FARM_HOUSE3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FARM HOUSE3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FARM_HOUSE4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FARM HOUSE4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frantisek_g_XXuVXLy5gHU_unsplash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frantisek-g-XXuVXLy5gHU-unsplash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FRESH_VEGGIE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FRESH VEGGIE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FRESH_VEGGIE1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FRESH VEGGIE1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FRESH_VEGGIE2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FRESH VEGGIE2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GARLIC_BREADSTICKS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GARLIC BREADSTICKS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GARLIC_BREADSTICKS1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GARLIC BREADSTICKS1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property INDI_CHICKEN_TIKKA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("INDI CHICKEN TIKKA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property INDI_CHICKEN_TIKKA1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("INDI CHICKEN TIKKA1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property INDI_CHICKEN_TIKKA2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("INDI CHICKEN TIKKA2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Indian_Rupee_symbol() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Indian-Rupee-symbol", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property INDIE_TANDOORI_PANEER() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("INDIE TANDOORI PANEER", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property INDIE_TANDOORI_PANEER1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("INDIE TANDOORI PANEER1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property INDIE_TANDOORI_PANEER2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("INDIE TANDOORI PANEER2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property key() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("key", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kids_stuff_pattern_vector() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kids-stuff-pattern-vector", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LIPTON_ICE_TEA__250ML_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LIPTON ICE TEA (250ML)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LIPTON_ICE_TEA__250ML_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LIPTON ICE TEA (250ML)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LIPTON_ICE_TEA__250ML_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LIPTON ICE TEA (250ML)2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Login_page2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Login page2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo_pizza_mania() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo-pizza-mania", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Margherita() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Margherita", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Margherita1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Margherita1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Margherita2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Margherita2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Margherita3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Margherita3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MEXICAN_GREEN_WAVE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MEXICAN GREEN WAVE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MEXICAN_GREEN_WAVE1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MEXICAN GREEN WAVE1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MEXICAN_GREEN_WAVE2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MEXICAN GREEN WAVE2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MIRINDA_500ML_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MIRINDA(500ML)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MIRINDA_500ML_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MIRINDA(500ML)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NON_VEG_SUPREME() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NON VEG SUPREME", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NON_VEG_SUPREME1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NON VEG SUPREME1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NON_VEG_SUPREME2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NON VEG SUPREME2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NON_VEG_SUPREME3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NON VEG SUPREME3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PANEER_MAKHANI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PANEER MAKHANI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PANEER_MAKHANI1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PANEER MAKHANI1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PANEER_MAKHANI2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PANEER MAKHANI2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PANEER_TIKKA_STUFFED_GARLIC_BREAD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PANEER TIKKA STUFFED GARLIC BREAD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PANEER_TIKKA_STUFFED_GARLIC_BREAD1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PANEER TIKKA STUFFED GARLIC BREAD1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PEPPER_BARBECUE___ONION() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PEPPER BARBECUE & ONION", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PEPPER_BARBECUE___ONION1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PEPPER BARBECUE & ONION1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PEPPER_BARBECUE___ONION2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PEPPER BARBECUE & ONION2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PEPPER_BARBECUE___ONION3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PEPPER BARBECUE & ONION3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PEPPER_BARBECUE_CHICKEN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PEPPER BARBECUE CHICKEN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PEPPER_BARBECUE_CHICKEN1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PEPPER BARBECUE CHICKEN1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PEPPER_BARBECUE_CHICKEN2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PEPPER BARBECUE CHICKEN2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PEPPY_PANEER() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PEPPY PANEER", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PEPPY_PANEER1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PEPPY PANEER1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PEPPY_PANEER2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PEPPY PANEER2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PEPPY_PANEER3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PEPPY PANEER3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PEPSI_500ML_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PEPSI(500ML)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PEPSI_500ML_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PEPSI(500ML)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PEPSI_BLACK_CAN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PEPSI BLACK CAN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PEPSI_BLACK_CAN1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PEPSI BLACK CAN1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pexels_pok_rie_982263() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pexels-pok-rie-982263", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property qr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("qr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Qr_code_reader() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Qr code reader", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property STUFFED_GARLIC_BREAD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("STUFFED GARLIC BREAD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property STUFFED_GARLIC_BREAD1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("STUFFED GARLIC BREAD1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Texture() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Texture", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Texture1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Texture1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Texture11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Texture11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Texture2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Texture2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Untitled_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Untitled-8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Untitled_8q() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Untitled-8q", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Untitled_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Untitled-9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property user() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VEG_EXTRAVAGANZA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VEG EXTRAVAGANZA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VEG_EXTRAVAGANZA1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VEG EXTRAVAGANZA1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VEG_EXTRAVAGANZA2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VEG EXTRAVAGANZA2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VEGGIE_PARADISE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VEGGIE PARADISE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VEGGIE_PARADISE1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VEGGIE PARADISE1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VEGGIE_PARADISE2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VEGGIE PARADISE2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
